name: Build Sega Genesis ROM
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/checkout@v3
      - name: Install Compiler
        run: npm install
      - name: Build ROM
        run: node index.js ./examples/test/project/startup.choice
      - name: Upload ROM
        uses: actions/upload-artifact@v3
        with:
          name: Sega-Genesis-ROM
          path: ./*.bin
